import pygame
pygame.font.init()
FPS_CAP = 60
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
BOARD_ROWS = 8
BOARD_COLUMNS = 8
SRC_DIRECTORY = "src\\"
SPRITES_DIRECTORY = SRC_DIRECTORY + "Data\\Sprites\\"
GAME_WIDTH = 800
GAME_HEIGHT = 800
UI_FONT = pygame.font.SysFont("Arial", 18)
